[build]
  command = "cd frontend && npx pnpm install && npx pnpm run build"
  publish = "frontend/dist"

[build.environment]
  NPM_FLAGS="--legacy-peer-deps"

# Redirect all routing to index.html for React SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
